// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_factorstochvol_RCPPEXPORTS_H_GEN_
#define RCPP_factorstochvol_RCPPEXPORTS_H_GEN_

#include "factorstochvol_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace factorstochvol {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("factorstochvol", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("factorstochvol", "_factorstochvol_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in factorstochvol");
            }
        }
    }

    inline void update_fsv(NumericMatrix facload_rcpp, NumericMatrix fac_rcpp, NumericMatrix logvar_rcpp, NumericVector logvar0_rcpp, NumericMatrix svpara_rcpp, NumericMatrix tau2_rcpp, NumericVector lambda2_rcpp, Rcpp::XPtr<arma::umat> curmixind_xptr, const arma::mat& y, const double& facloadtol, const arma::imat& restriction, const arma::uvec& facloadtunrestrictedelements, const arma::irowvec& nonzerospercol, const arma::icolvec& nonzerosperrow, const Rcpp::NumericVector priorh0, const bool& ngprior, const bool& columnwise, const Rcpp::NumericVector aShrink, const Rcpp::NumericVector cShrink, const Rcpp::NumericVector dShrink, const Rcpp::NumericMatrix priorhomoskedastic, const double& offset, const Rcpp::NumericVector heteroskedastic, const int& interweaving, const Rcpp::XPtr<stochvol::ExpertSpec_FastSV> expert_idi_ptr, const Rcpp::XPtr<stochvol::ExpertSpec_FastSV> expert_fac_ptr, const Rcpp::XPtr<std::vector<stochvol::PriorSpec>> prior_specs_ptr, const double& B011inv, const bool& samplefac, const bool& signswitch, const int& i) {
        typedef SEXP(*Ptr_update_fsv)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_update_fsv p_update_fsv = NULL;
        if (p_update_fsv == NULL) {
            validateSignature("void(*update_fsv)(NumericMatrix,NumericMatrix,NumericMatrix,NumericVector,NumericMatrix,NumericMatrix,NumericVector,Rcpp::XPtr<arma::umat>,const arma::mat&,const double&,const arma::imat&,const arma::uvec&,const arma::irowvec&,const arma::icolvec&,const Rcpp::NumericVector,const bool&,const bool&,const Rcpp::NumericVector,const Rcpp::NumericVector,const Rcpp::NumericVector,const Rcpp::NumericMatrix,const double&,const Rcpp::NumericVector,const int&,const Rcpp::XPtr<stochvol::ExpertSpec_FastSV>,const Rcpp::XPtr<stochvol::ExpertSpec_FastSV>,const Rcpp::XPtr<std::vector<stochvol::PriorSpec>>,const double&,const bool&,const bool&,const int&)");
            p_update_fsv = (Ptr_update_fsv)R_GetCCallable("factorstochvol", "_factorstochvol_update_fsv");
        }
        RObject rcpp_result_gen;
        {
            rcpp_result_gen = p_update_fsv(Shield<SEXP>(Rcpp::wrap(facload_rcpp)), Shield<SEXP>(Rcpp::wrap(fac_rcpp)), Shield<SEXP>(Rcpp::wrap(logvar_rcpp)), Shield<SEXP>(Rcpp::wrap(logvar0_rcpp)), Shield<SEXP>(Rcpp::wrap(svpara_rcpp)), Shield<SEXP>(Rcpp::wrap(tau2_rcpp)), Shield<SEXP>(Rcpp::wrap(lambda2_rcpp)), Shield<SEXP>(Rcpp::wrap(curmixind_xptr)), Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(facloadtol)), Shield<SEXP>(Rcpp::wrap(restriction)), Shield<SEXP>(Rcpp::wrap(facloadtunrestrictedelements)), Shield<SEXP>(Rcpp::wrap(nonzerospercol)), Shield<SEXP>(Rcpp::wrap(nonzerosperrow)), Shield<SEXP>(Rcpp::wrap(priorh0)), Shield<SEXP>(Rcpp::wrap(ngprior)), Shield<SEXP>(Rcpp::wrap(columnwise)), Shield<SEXP>(Rcpp::wrap(aShrink)), Shield<SEXP>(Rcpp::wrap(cShrink)), Shield<SEXP>(Rcpp::wrap(dShrink)), Shield<SEXP>(Rcpp::wrap(priorhomoskedastic)), Shield<SEXP>(Rcpp::wrap(offset)), Shield<SEXP>(Rcpp::wrap(heteroskedastic)), Shield<SEXP>(Rcpp::wrap(interweaving)), Shield<SEXP>(Rcpp::wrap(expert_idi_ptr)), Shield<SEXP>(Rcpp::wrap(expert_fac_ptr)), Shield<SEXP>(Rcpp::wrap(prior_specs_ptr)), Shield<SEXP>(Rcpp::wrap(B011inv)), Shield<SEXP>(Rcpp::wrap(samplefac)), Shield<SEXP>(Rcpp::wrap(signswitch)), Shield<SEXP>(Rcpp::wrap(i)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

}

#endif // RCPP_factorstochvol_RCPPEXPORTS_H_GEN_
